/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/TlQwpf76qKz
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet"
import { Button } from "@/components/ui/button"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Card, CardContent } from "@/components/ui/card"

export function hola() {
  return (
    (<div className="flex flex-col min-h-screen md:h-screen">
      <header
        className="bg-blue-500 text-primary-foreground p-4 flex items-center justify-between md:hidden">
        <Link href="#" className="text-xl font-bold" prefetch={false}>
          Travel Admin
        </Link>
        <Sheet>
          <SheetTrigger asChild>
            <Button variant="outline" size="icon" className="rounded-full">
              <MenuIcon className="w-6 h-6" />
              <span className="sr-only">Toggle navigation</span>
            </Button>
          </SheetTrigger>
          <SheetContent side="left">
            <nav className="flex flex-col gap-4 mt-8">
              <Link href="#" className="hover:text-primary" prefetch={false}>
                Hotels
              </Link>
              <Link href="#" className="hover:text-primary" prefetch={false}>
                Rooms
              </Link>
              <Link href="#" className="hover:text-primary" prefetch={false}>
                Services
              </Link>
              <Link href="#" className="hover:text-primary" prefetch={false}>
                Ski Passes
              </Link>
              <Link href="#" className="hover:text-primary" prefetch={false}>
                Transport
              </Link>
            </nav>
            <div className="flex items-center gap-4 mt-auto">
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="outline" size="icon" className="rounded-full">
                    <img
                      src="/placeholder.svg"
                      width={32}
                      height={32}
                      alt="Avatar"
                      className="rounded-full" />
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                  <DropdownMenuLabel>Admin Account</DropdownMenuLabel>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem>Settings</DropdownMenuItem>
                  <DropdownMenuItem>Logout</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </SheetContent>
        </Sheet>
      </header>
      <div className="flex flex-1 md:h-full">
        <aside
          className="bg-blue-500 text-primary-foreground p-6 flex flex-col hidden md:flex">
          <Link href="#" className="text-xl font-bold" prefetch={false}>
            Travel Admin
          </Link>
          <nav className="flex-1 flex flex-col gap-4 mt-8">
            <Link href="#" className="hover:text-primary" prefetch={false}>
              Hotels
            </Link>
            <Link href="#" className="hover:text-primary" prefetch={false}>
              Rooms
            </Link>
            <Link href="#" className="hover:text-primary" prefetch={false}>
              Services
            </Link>
            <Link href="#" className="hover:text-primary" prefetch={false}>
              Ski Passes
            </Link>
            <Link href="#" className="hover:text-primary" prefetch={false}>
              Transport
            </Link>
          </nav>
          <div className="flex items-center gap-4">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="outline" size="icon" className="rounded-full">
                  <img
                    src="/placeholder.svg"
                    width={32}
                    height={32}
                    alt="Avatar"
                    className="rounded-full" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuLabel>Admin Account</DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuItem>Settings</DropdownMenuItem>
                <DropdownMenuItem>Logout</DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </aside>
        <div className="flex-1 p-8 md:h-full">
          <div className="grid grid-cols-1 md:grid-cols-[1fr] gap-8 h-full">
            <section className="col-span-1 md:col-span-2 h-full">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-2xl font-bold">Hotels</h2>
                <Link
                  href="#"
                  className="bg-blue-500 hover:bg-blue-600 text-primary-foreground rounded-full p-2"
                  prefetch={false}>
                  <PlusIcon className="w-6 h-6" />
                  <span className="sr-only">Add New Hotel</span>
                </Link>
              </div>
              <div className="grid gap-4 h-full">
                <Card className="h-full">
                  <CardContent className="h-full">
                    <div className="flex items-center justify-between h-full">
                      <div>
                        <h3 className="text-xl font-bold">Hotel Ritz-Carlton</h3>
                        <p className="text-muted-foreground">Paris, France</p>
                      </div>
                      <div className="flex items-center gap-2">
                        <StarIcon className="w-5 h-5 fill-yellow-500" />
                        <span className="font-bold">5</span>
                      </div>
                    </div>
                    <div className="flex items-center justify-between mt-4">
                      <p className="text-muted-foreground">200 Rooms</p>
                      <Button variant="outline">View Details</Button>
                    </div>
                  </CardContent>
                </Card>
                <Card className="h-full">
                  <CardContent className="h-full">
                    <div className="flex items-center justify-between h-full">
                      <div>
                        <h3 className="text-xl font-bold">Four Seasons Resort</h3>
                        <p className="text-muted-foreground">Bora Bora, French Polynesia</p>
                      </div>
                      <div className="flex items-center gap-2">
                        <StarIcon className="w-5 h-5 fill-yellow-500" />
                        <span className="font-bold">5</span>
                      </div>
                    </div>
                    <div className="flex items-center justify-between mt-4">
                      <p className="text-muted-foreground">100 Rooms</p>
                      <Button variant="outline">View Details</Button>
                    </div>
                  </CardContent>
                </Card>
                <Card className="h-full">
                  <CardContent className="h-full">
                    <div className="flex items-center justify-between h-full">
                      <div>
                        <h3 className="text-xl font-bold">Atlantis Paradise Island</h3>
                        <p className="text-muted-foreground">Nassau, Bahamas</p>
                      </div>
                      <div className="flex items-center gap-2">
                        <StarIcon className="w-5 h-5 fill-yellow-500" />
                        <span className="font-bold">4</span>
                      </div>
                    </div>
                    <div className="flex items-center justify-between mt-4">
                      <p className="text-muted-foreground">1,201 Rooms</p>
                      <Button variant="outline">View Details</Button>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>)
  );
}

function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function PlusIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>)
  );
}


function StarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon
        points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
